# Generated by Django 6.1 on 2026-08-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='inventory.variant'),
        ),
    ]
