# Generated by Django 6.1 on 2026-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_vehicle_vehicle_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('IN_TRANSIT', 'In Transit'), ('RESERVED', 'Reserved'), ('TEST_DRIVE', 'Test Drive'), ('SOLD', 'Sold'), ('DELIVERED', 'Delivered'), ('SERVICE', 'Service'), ('DAMAGED', 'Damaged')], default='IN_STOCK', max_length=20),
        ),
    ]
