# Generated by Django 6.1 on 2026-09-01 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_vehicle_status'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Current location of this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='locations.location'),
        ),
    ]
