# Generated by Django 6.1 on 2026-09-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vehicle_current_location'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_movements_from', to='locations.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_movements_to', to='locations.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.vehicle')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
    ]
